#nullable disable
namespace LICC.AST.Builders.Pseudo
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     ANTLR Version: 4.7.1
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    // Generated from Pseudo.g4 by ANTLR 4.7.1

    // Unreachable code detected
#pragma warning disable 0162
    // The variable '...' is assigned but its value is never used
#pragma warning disable 0219
    // Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
    // Ambiguous reference in cref attribute
#pragma warning disable 419


    using Antlr4.Runtime.Misc;
    using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
    using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
    using IToken = Antlr4.Runtime.IToken;
    using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

    /// <summary>
    /// This class provides an empty implementation of <see cref="IPseudoListener"/>,
    /// which can be extended to create a listener which only needs to handle a subset
    /// of the available methods.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
    [System.CLSCompliant(false)]
    public partial class PseudoBaseListener : IPseudoListener
    {
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.unit"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterUnit([NotNull] PseudoParser.UnitContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.unit"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitUnit([NotNull] PseudoParser.UnitContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.block"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterBlock([NotNull] PseudoParser.BlockContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.block"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitBlock([NotNull] PseudoParser.BlockContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.statement"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterStatement([NotNull] PseudoParser.StatementContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.statement"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitStatement([NotNull] PseudoParser.StatementContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.declaration"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterDeclaration([NotNull] PseudoParser.DeclarationContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.declaration"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitDeclaration([NotNull] PseudoParser.DeclarationContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.parlist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterParlist([NotNull] PseudoParser.ParlistContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.parlist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitParlist([NotNull] PseudoParser.ParlistContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.assignment"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterAssignment([NotNull] PseudoParser.AssignmentContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.assignment"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitAssignment([NotNull] PseudoParser.AssignmentContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterExp([NotNull] PseudoParser.ExpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.exp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitExp([NotNull] PseudoParser.ExpContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.aexp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterAexp([NotNull] PseudoParser.AexpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.aexp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitAexp([NotNull] PseudoParser.AexpContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.lexp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterLexp([NotNull] PseudoParser.LexpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.lexp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitLexp([NotNull] PseudoParser.LexpContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.aop"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterAop([NotNull] PseudoParser.AopContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.aop"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitAop([NotNull] PseudoParser.AopContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.rop"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterRop([NotNull] PseudoParser.RopContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.rop"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitRop([NotNull] PseudoParser.RopContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.lop"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterLop([NotNull] PseudoParser.LopContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.lop"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitLop([NotNull] PseudoParser.LopContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.uop"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterUop([NotNull] PseudoParser.UopContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.uop"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitUop([NotNull] PseudoParser.UopContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.cexp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterCexp([NotNull] PseudoParser.CexpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.cexp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitCexp([NotNull] PseudoParser.CexpContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.explist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterExplist([NotNull] PseudoParser.ExplistContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.explist"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitExplist([NotNull] PseudoParser.ExplistContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.literal"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterLiteral([NotNull] PseudoParser.LiteralContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.literal"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitLiteral([NotNull] PseudoParser.LiteralContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.type"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterType([NotNull] PseudoParser.TypeContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.type"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitType([NotNull] PseudoParser.TypeContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.typename"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterTypename([NotNull] PseudoParser.TypenameContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.typename"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitTypename([NotNull] PseudoParser.TypenameContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.var"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterVar([NotNull] PseudoParser.VarContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.var"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitVar([NotNull] PseudoParser.VarContext context) { }
        /// <summary>
        /// Enter a parse tree produced by <see cref="PseudoParser.iexp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void EnterIexp([NotNull] PseudoParser.IexpContext context) { }
        /// <summary>
        /// Exit a parse tree produced by <see cref="PseudoParser.iexp"/>.
        /// <para>The default implementation does nothing.</para>
        /// </summary>
        /// <param name="context">The parse tree.</param>
        public virtual void ExitIexp([NotNull] PseudoParser.IexpContext context) { }

        /// <inheritdoc/>
        /// <remarks>The default implementation does nothing.</remarks>
        public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
        /// <inheritdoc/>
        /// <remarks>The default implementation does nothing.</remarks>
        public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
        /// <inheritdoc/>
        /// <remarks>The default implementation does nothing.</remarks>
        public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
        /// <inheritdoc/>
        /// <remarks>The default implementation does nothing.</remarks>
        public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
    }
}